# Generated by Django 3.1 on 2020-11-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
