# Generated by Django 3.1 on 2020-11-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_store_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_image',
            name='default_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='header_image',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
