# Generated by Django 3.1 on 2020-11-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201109_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Inprocess', 'Inprocess'), ('out for delivery', 'out for delivery'), ('successfully delivered', 'successfully delivered')], default='Inprocess', max_length=50),
        ),
    ]
