# Generated by Django 3.1 on 2020-11-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='master_key',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
