# Generated by Django 3.1 on 2020-11-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
