# Generated by Django 3.1 on 2020-11-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201127_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
