# Generated by Django 3.1 on 2020-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
