# Generated by Django 3.1 on 2020-11-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_contact_us_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
