# Generated by Django 3.1 on 2020-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20201130_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
