# Generated by Django 3.1 on 2020-12-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20201130_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mobile',
            new_name='mobile_num',
        ),
    ]
