# Generated by Django 3.1 on 2020-12-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20201201_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='booklet',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='end_offer_time',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='order_persent',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start_offer_time',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_for',
            field=models.CharField(choices=[('All User', 'All User'), ('First user', 'First user')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product_master_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.store'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
