# Generated by Django 3.1 on 2020-12-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
