# Generated by Django 3.1 on 2020-12-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='COD',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'COD'), ('ONLINE PAY', 'ONLINE PAY')], default='ONLINE PAY', max_length=50),
        ),
    ]
