# Generated by Django 3.1 on 2020-12-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20201213_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchisses',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
