# Generated by Django 3.1 on 2021-01-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20201215_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
