# Generated by Django 3.1 on 2021-01-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_order_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bankTxnId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='txnId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
