# Generated by Django 3.1 on 2021-01-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20210125_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='store_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
