# Generated by Django 3.1 on 2021-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_cart_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
