# Generated by Django 3.1 on 2021-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_store_is_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='MERCHANT_KEY',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='MID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
