# Generated by Django 3.1 on 2021-04-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0043_auto_20210406_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storeheader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
                ('default_image', models.BooleanField(default=False)),
                ('is_enable', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.store')),
            ],
        ),
    ]
