# Generated by Django 3.1 on 2020-11-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_positions',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right'), ('center', 'center')], default='left', max_length=50),
        ),
    ]
