# Generated by Django 3.1 on 2020-11-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201122_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='blog_Category',
        ),
    ]
