# Generated by Django 3.1 on 2020-11-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_master_key'),
        ('blog', '0004_auto_20201122_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.DeleteModel(
            name='blog_Category',
        ),
    ]
