# Generated by Django 3.1 on 2020-11-27 10:01

from django.db import migrations, models
import rocapi.models.user_profile


class Migration(migrations.Migration):

    dependencies = [
        ('rocapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(default='profile/avatar.jpg', upload_to=rocapi.models.user_profile.directory_path),
        ),
    ]
